# Generated by Django 4.2.3 on 2023-07-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_completed', '-created_at']},
        ),
    ]
