# Generated by Django 4.2.3 on 2023-07-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-created_at']},
        ),
    ]
